### ISSUE TITLE
IMM Review

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Extensions.CosmosDb#54]
Go through every item on the IP Maturity Matrix and ensure it is up to date, adding work items in any areas that could be improved

- [x] **Shared Engineering Standards**
- [x] **Coding Standards**
- [x] **Executable Specifications**
- [x] **Code Coverage**
- [x] **Benchmarks**
- [x] **Reference Documentation**
- [x] **Design & Implementation Documentation** #83 
- [x] **How-to Documentation**
- [x] **Date of Last IP Review**
- [x] **Framework Version**
- [x] **Associated Work Items** #85
- [x] **Source Code Availability**
- [x] **License**: Apache 2.0
- [x] **Production Use**
- [x] **Insights** #86
- [x] **Packaging** #87
- [x] **Deployment**
- [x] **Next IMM review** #88
